# Generated by Django 5.1.7 on 2025-03-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_id',
        ),
        migrations.AddField(
            model_name='flight',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
